Use dynamic vocab_size for llama (#891)
This PR uses a `tvm.tir.Var` to represent the `vocab_size` when compiling Llama models. 

The goal is to reuse Llama-2's model library when running its model variants like WizardMath. The default `vocab_size` is `32000`, but some models can have `32001`. 

Previous behavior:
```python
from mlc_chat import ChatModule
cm = ChatModule(
    model="dist/mlc-chat-WizardMath-7B-V1.0-q4f16_1",
    lib_path="dist/Llama-2-7b-chat-hf-q4f16_1/Llama-2-7b-chat-hf-q4f16_1-cuda.so"
)
output = cm.generate(prompt="hi")
```

```bash
Traceback (most recent call last):
...
RuntimeError: Check failed: input_shape[i] == reg (32001 vs. 32000) : ErrorContext(fn=prefill, loc=param[3], param=params, annotation=R.Tuple(R.Tensor((32000, 512), dtype="uint32"), ...)  match_cast error,  shape[0] mismatch to specified constant.
```

After this PR, the code above can run without an error.

Tested:
- Compiled Llama2 7B's model library and used it to run WizardMath's model
- Confirmed that there is no performance regression despite the dynamic size (on RTX 4090)