[Fix] Fix windows build (#901)
MSVC we are using in nightly wheels doesn't seem to support implicit
conversion from `std::filesystem::path` to `std::string` according to
the error messages below:

```
llm_chat.cc(211,44): error C2664: 'std::string mlc::llm::LoadBytesFromFile(const std::string &)': cannot convert argument 1 from 'std::filesystem::path' to 'const std::string &' [D:\a\package\package\mlc-llm\build\mlc_llm_objs.vcxproj]
llm_chat.cc(212,32): error C2664: 'std::string mlc::llm::LoadBytesFromFile(const std::string &)': cannot convert argument 1 from 'std::filesystem::path' to 'const std::string &' [D:\a\package\package\mlc-llm\build\mlc_llm_objs.vcxproj]
llm_chat.cc(217,1): error C2738: 'operator std::basic_string<char,std::char_traits<char>,std::allocator<char>>': is ambiguous or is not a member of 'std::filesystem::path' [D:\a\package\package\mlc-llm\build\mlc_llm_objs.vcxproj]
```

This PR introduces a fix that explicitly convert
`std::filesystem::path` to string.